/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jbudget105333;

import java.io.IOException;

public class App {

    private final BudgetReportController controller;
    private final View view;

    //Costruttore di App che prende un Controller di budgetReport e una View
    public App(BudgetReportController controller, View view) {
        this.controller = controller;
        this.view = view;
    }

    //Metodo main che genera un'App con un factory method e vi esegue il metodo start
    public static void main(String[] args) {
        createAppBase().start();
    }

    //Metodo start che fa partire il metodo open con parametro un viewController e metodo close della view
    private void start() {
        try {
            this.view.open(new ViewBaseController(this.controller));
        } catch (IOException e) {
            e.printStackTrace();
        }
        this.view.close();
    }

    //Factory method che crea l'App da un budgetReportController e una View
    private static App createAppBase() {
        LedgerController lcontroller = new LedgerBaseController();
        BudgetController bcontroller = new BudgetBaseController(lcontroller);
        BudgetReportController brcontroller = new BudgetReportBaseController(lcontroller,bcontroller);
        View view = new ConsoleView();
        return  new App(brcontroller,view);
    }

}
