/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jbudget105333;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.HashMap;
import java.util.function.Consumer;

public class App<B extends Bilancio> {

    private View<B> view;
    private Comandi<B> comandi;
    private Store<B> store;

    public App(View<B> consoleView, Comandi<B> comandi, Store<B> store) {
        this.view = consoleView;
        this.comandi = comandi;
        this.store = store;
    }

    public static void main(String[] args) {
        try{
            createBilancio().start();
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    public static App createBilancio() throws FileNotFoundException {
        Bilancio b = new BilancioSemplice();
        Comandi<? extends Bilancio> comandi = new ComandiHashMap(new HashMap<>(),b);
        comandi.addComandi(createBaseCommand());
        comandi.addComandi(createShowCommand());
        comandi.addComando("help",s->System.out.println(comandi.getComandi().keySet().toString()));
        View v = new ConsoleView(new BilancioSemplicePrinter());
        return new App(v,comandi,new FileStore());
    }

    private void start() throws IOException {
        this.store.read(this.comandi.getGestoreMovimenti());
        this.view.open(this.comandi);
        this.store.write(this.comandi.getGestoreMovimenti());
        this.view.close();
        this.store.close();
    }

    private static HashMap<String, Consumer<? extends Bilancio>> createBaseCommand(){
        HashMap<String, Consumer<? extends Bilancio>> commands = new HashMap<>();
        commands.put("exit",s->s.shutdown());
        return commands;
    }

    private static HashMap<String, Consumer<? extends Bilancio>> createShowCommand() {
        HashMap<String, Consumer<? extends Bilancio>> commands = new HashMap<>();
        commands.put("tagin",s->System.out.println(TagPrinter.stringTagIn()));
        commands.put("tagout",s->System.out.println(TagPrinter.stringTagOut()));
        commands.put("pi",s->System.out.println("pi(piano istantaneo) value tags"));
        commands.put("pp",s->System.out.println("pp(piano programmato) value tags date(anno:mese:giorno)"));
        commands.put("pm",s->System.out.println
                ("pm(piano mensile) value tags dateStart(anno:mese:giorno)-dateStop(anno:mese:giorno)"));
        commands.put("gd",s->System.out.println
                ("gd(gestore movimenti date) dateStart(anno:mese:giorno)-dateStop(anno:mese:giorno)"));
        commands.put("gt",s->System.out.println
                ("gt(gestore movimenti tags) tags"));
        commands.put("showall",s->System.out.println
                ("showall movimenti: sho"));
        return commands;
    }

}
